# Generated by Django 2.1.1 on 2018-09-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_auto_20180908_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
