# Generated by Django 2.1.1 on 2018-09-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_alertresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alert.AlertResponse'),
        ),
    ]
