# Generated by Django 2.1.1 on 2018-09-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0004_alert_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertresponse',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Bassa'), (2, 'Media'), (3, 'Alta')], default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='alertresponse',
            name='security_issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertresponse',
            name='status',
            field=models.CharField(choices=[('accepted', 'Presa in carico'), ('resolved', 'Risolta'), ('invalid', 'Invalida')], default='accepted', max_length=100),
        ),
    ]
