# Generated by Django 2.1.1 on 2018-09-08 19:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0007_auto_20180908_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='lon',
        ),
        migrations.AddField(
            model_name='alert',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
