# Generated by Django 2.1.1 on 2018-09-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0009_auto_20180908_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertresponse',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertresponse',
            name='resolution_estimate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
